version: '3.8'
services:
    mongodb:
        ports:
            - '27017:27017'
        volumes:
            - '~/mongodb/database:/data/db'
        restart: unless-stopped
        image: mongo
        container_name: mongodb
        environment:
          - PUID=1000
          - PGID=1000
    sqlserv:
        ports:
            - '1433:1433'
        volumes:
            - '~/sqlserv/database:/data/db'
        restart: unless-stopped
        image: microsoft/mssql-server-linux:2017-latest
        container_name: sqlserv
        environment:
          - ACCEPT_EULA=Y
          - SA_PASSWORD=cesimanger1234ABC
          - PUID=1000
          - PGID=1000
