version: '3.8'
services:
    mongodb:
        ports:
            - '27017:27017'
        volumes:
            - './Docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro'
        restart: unless-stopped
        image: mongo
        container_name: mongodb
        environment:
          MONGO_INITDB_ROOT_USERNAME: sa
          MONGO_INITDB_ROOT_PASSWORD: cesimanger1234ABC
          MONGO_INITDB_DATABASE: cesiManger
    sqlserv:
        build:
            context: ./Docker
            dockerfile: Dockerfile
        ports:
            - '1433:1433'
        volumes:
            - './DB/sqlserver/database:/data/db'
        restart: unless-stopped
        image: microsoft/mssql-server-linux:2017-latest
        container_name: sqlserv
        environment:
          - ACCEPT_EULA=Y
          - SA_PASSWORD=cesimanger1234ABC
          - PUID=1000
          - PGID=1000
